#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

nitrogen --restore &
picom --experimental-backend &
xrandr --output HDMI-1-1 --auto --left-of eDP-1 --rotate left &
cd /home/z/xborder && ./xborders --config /home/z/.config/xborder/conf.json &
# dunst --config "~/.config/dunst/dunstrc" &
/bin/sh ~/.config/i3/scripts/polybarstart.sh &
exec i3 -c ~/.config/i3/config && xset s off

